### ISSUE TITLE
pyusb multiple devices

### ISSUE THREAD

**Issue by masnatacion** [pklaus/brother_ql#20]
hi
how can i print if i have multiple devices with the same brand and product?

thank u

**Comment by pklaus** [comment]
Hi masnatacion, you can provide a connection string like the following:
`usb://0x04f9:0x209d/000M6Z401370`
This consists of:
`usb://idVendor:idProduct/iSerialNumber`
which is unique because of the serial number.

In commit 00c2cb9 i fixed the documentation in the source code and in the README.
