### ISSUE TITLE
Cannot print 24 dia labels

### ISSUE THREAD

**Issue by mark77-DE** [pklaus/brother_ql#21]
While trying to create 24mm diameter labels, an error about mismatching picture dimentions occurs.

Interesting is, when you add:
`
logger.warning(im.size[0])
logger.warning(im.size[1])
logger.warning(dots_printable[0])
logger.warning(dots_printable[1])`
to "brother_ql_create.py", it will output 236 for each warning.

Anyhow, it will exit on:
`if im.size[0] != dots_printable[0] or im.size[1] != dots_printable[1]:
sys.exit("Check your image dimensions. Expecting: " + str(dots_printable))`

**Comment by pklaus** [comment]
Thanks for reporting an issue.

I changed the reporting in the `sys.exit()` line in commit ee69e04. Could you please upgrade the package to the latest version on Github using:

    pip install --upgrade https://github.com/pklaus/brother_ql/archive/master.zip

And check again what the output is? Also, can you please add the image (or another example image of the same size) to this issue?

**Comment by mark77-DE** [comment]
Thats working now, thanks a lot!



![236x236](https://user-images.githubusercontent.com/31760710/30542822-141a7960-9c81-11e7-9f05-38d3ff0ea477.jpg)
