### ISSUE TITLE
Numpy dependency

### ISSUE THREAD

**Issue by shopro** [pklaus/brother_ql#26]
reader.py on line 10 is importing Numpy but it isn't needed/used in the module. Seems to be a leftover from old code that is causing errors since it's not installed.

**Comment by pklaus** [comment]
Thanks for reporting this. I removed the dependency in commit 32ba70b and the next release will contain the fix.

**Comment by pklaus** [comment]
Thanks again for reporting. The fix is now part of the latest release [v0.8.4](https://github.com/pklaus/brother_ql/releases/tag/v0.8.4).
