### ISSUE TITLE
Extra Label Size

### ISSUE THREAD

**Issue by i6media** [pklaus/brother_ql#27]
Hi,

Thanks for your awesome package, works like a charm!

There is however one thing, we've purchased a Brother QL-1060N, with address labels. The format looks like it's 102x152 mm, but it is 102x153 mm.

That means it flashes red when printing in the 102x152 format.

We've modified devicedependent.py ourselves, and added the extra label size, however if other people experience the same problem, permanent implementation in the repository would be great:

`"102x153":{'tape_size': (102, 153), 'dots_total': (1200, 1804), 'dots_printable': (1164, 1660), 'right_margin_dots': 12, 'feed_margin':  0},`

Keep up the good work!

**Comment by pklaus** [comment]
Great, thanks for this report. I'm happy someone can confirm the QL-1060N to work.
So printing works nicely with the added line? Did you try any other label sizes, too?

**Comment by i6media** [comment]
I didn't try other formats, but I did investigate some more:

Even on the cardboard package (Brother DK-11241) it says 102x152mm Address Label, however on the printer verbose log it says 'currently installed: 102x153mm'.

With the added line on devicedependent.py it works like a charm.

**Comment by pklaus** [comment]
Good, thanks for letting me know.

If Brother is advertising it that way, I think I should change the label specification line to state `'tape_size': (102, 153),` but leave the label identifier (for the command line) as `102x152`.

**Comment by pklaus** [comment]
Commit e5d4fde should fix this issue. I kept the previous label-size identifier `"102x152"`. Behind the scenes, however, the package is now using the 102x153 info. Thanks for reporting this!
