### ISSUE TITLE
Python 2.7 compatibility

### ISSUE THREAD

**Issue by spidfire** [pklaus/brother_ql#35]
> NOTE: Do not merge without a 3.0 fix  (it's a 2.7 only fix)

https://github.com/spidfire/brother_ql/blob/master/brother_ql/reader.py

during the use of brother_ql_print it got an error of unable to convert str to int

I've created a python 2.7 fix (it doesn't work with py3+) 

it fixes the problem of that a bytearray element like `data[1]` returns a string in 2.7 and a int in 3+

**Comment by pklaus** [comment]
Thanks for sharing those changes. I'll do some testing on Py3 in order to ensure compatibility with both. Probably the minimum 3.x version I'll support is 3.3 or 3.4. Might take me another week to find the time to complete testing.

**Comment by spidfire** [comment]
Nice thx :+1:

**Comment by pklaus** [comment]
The required change in fd22068 was even simpler.
That's the advantage of using the `from builtins import bytes` import statement provided by the [future](https://pypi.org/project/future/) Py2/Py3 compatibility layer package.

Thanks again.
