### ISSUE TITLE
Vote or help packaging for Ubuntu/Debian

### ISSUE THREAD

**Issue by PanderMusubi** [pklaus/brother_ql#4]
Please, vote or help packaging for Ubuntu/Debian via https://bugs.launchpad.net/ubuntu/+bug/1625588

**Comment by pklaus** [comment]
Great to see the interest in an Ubuntu/Debian package. Unfortunately I'm busy the next two weeks and cannot help until then.

**Comment by pklaus** [comment]
Thanks for considering to create an Ubuntu/Debian package. Please let me know how to help with the packaging. Without more input I will close this issue soon. In case you encounter any problems, don't hesitate to file a new issue.
