### ISSUE TITLE
Call brother_ql from PHP

### ISSUE THREAD

**Issue by j99ht** [pklaus/brother_ql#45]
Is there is a way to call brother_ql from a php script?

I'm trying it but I get this error

`Traceback (most recent call last): File "/usr/bin/brother_ql", line 7, in from brother_ql.cli import cli ImportError: No module named brother_ql.cli
`

**Comment by pklaus** [comment]
You can without a doubt use the brother_ql tool from other software and many do this succesfully. Could you please state how you were installing brother_ql and paste the output of running the following command in the terminal:

    brother_ql info env

**Comment by pklaus** [comment]
Thanks for posting the status output. It shows that you installed the package in your user directory:

    package location: /home/myhome/.local/lib/python2.7/site-packages

The reason being that `pip install somepackage` defaults to `pip install --user somepackage` on Ubuntu.

Please consider installing the package system wide with `sudo pip install brother_ql` or run your PHP server under the same user as the one you installed the package with `pip` on the command line.

**Comment by pklaus** [comment]
So just to check: Did this solve the issue for you?

**Comment by j99ht** [comment]
It worked. Thanks a lot

**Comment by pklaus** [comment]
OK, great. Let me know if there is something you think could be improved (ideally in a new issue or via email).
