### ISSUE TITLE
Fix for error: invalid command 'bdist_wheel'

### ISSUE THREAD

**Issue by PanderMusubi** [pklaus/brother_ql#5]
When installing getting the error:

```
error: invalid command 'bdist_wheel'
...
Failed building wheel for packbits
```

do first

```
sudo apt-get install python-wheel
```

Please add this to the documentation.

**Comment by pklaus** [comment]
I'm not sure about this issue. First of all, I'm surprised that the package is not installed by default. Secondly, where is the right place for this dependency? Maybe ustream in an `install_requires` statement in [packbit's setup.py](https://github.com/psd-tools/packbits/blob/master/setup.py)?

**Comment by pklaus** [comment]
I'm going to close this issue soon if no further information will be added about the problem.
